### PR TITLE
Update test.spec.js

### PR DESCRIPTION
**Pull request by mrmarcsmith**
added tests for additional methods of passing S3 Overrides.

### CODE REVIEW

**Comment by mrmarcsmith** [comment]
Hi All,
I have fixed this conflict but it needs approval from someone with write access

**Comment by flovilmart** [comment]
@mrmarcsmith thanks for extending the coverage! Let's wait for the CI to finish before merging those.

**Comment by mrmarcsmith** [comment]
Hi @flovilmart ,
On my end it says "This Branch has a conflict that must be resolved". I updated my commit to correct the conflict but the merge needs approval before the CI can kick in. here is the link to review: https://github.com/parse-server-modules/parse-server-s3-adapter/pull/39/conflicts

**Comment by flovilmart** [comment]
Seems that your commit didn't fix the conflicts but now it's ok

**Comment by mrmarcsmith** [comment]
@flovilmart this test checks pull request https://github.com/parse-server-modules/parse-server-s3-adapter/pull/37 which hasn't been approved yet. I was asked by @acinader to write this test before he would approve it.

**Comment by acinader** [comment]
ah, I see.  so, in your local box you should rebase (or merge) patch-2 onto patch-1 and then push it to git hub.  that way the two commits will show up in the same pr and we can see the test passing.

k?  If you're not sure how to do, I could do for you....

**Comment by mrmarcsmith** [comment]
this issue was moved to PR #40

**Comment by flovilmart** [comment]
Closing as moved to #40

**Pull request closed without merging**
